baseURL = "/"
languageCode = "en-us"
title = "The Mederos"
googleAnalytics = "UA-404975-5"
canonifyurls = false
pluralizeListTitles = false
disableKinds = ["taxonomy","taxonomyTerm"]

[params]
  domain_name = "medero.net"
  description = ""
  
[permalinks]
	pages = "/pages/:slug"
	family = "/family/:slug"